/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PlantButton {
        /**
          * The type of form submission associated with the button.
          * @default 'button'
         */
        "type": "button" | "reset" | "submit";
    }
    interface PlantButtonItem {
    }
    interface PlantCard {
    }
}
declare global {
    interface HTMLPlantButtonElement extends Components.PlantButton, HTMLStencilElement {
    }
    var HTMLPlantButtonElement: {
        prototype: HTMLPlantButtonElement;
        new (): HTMLPlantButtonElement;
    };
    interface HTMLPlantButtonItemElement extends Components.PlantButtonItem, HTMLStencilElement {
    }
    var HTMLPlantButtonItemElement: {
        prototype: HTMLPlantButtonItemElement;
        new (): HTMLPlantButtonItemElement;
    };
    interface HTMLPlantCardElement extends Components.PlantCard, HTMLStencilElement {
    }
    var HTMLPlantCardElement: {
        prototype: HTMLPlantCardElement;
        new (): HTMLPlantCardElement;
    };
    interface HTMLElementTagNameMap {
        "plant-button": HTMLPlantButtonElement;
        "plant-button-item": HTMLPlantButtonItemElement;
        "plant-card": HTMLPlantCardElement;
    }
}
declare namespace LocalJSX {
    interface PlantButton {
        /**
          * If `true`, the user cannot interact with the element.
         */
        "disabled"?: boolean;
        /**
          * The `id` of a `<form>` element to associate this element with.
         */
        "form"?: string;
        /**
          * The name of the element, used when submitting an HTML form.
         */
        "name"?: string;
        /**
          * The type of form submission associated with the button.
          * @default 'button'
         */
        "type"?: "button" | "reset" | "submit";
    }
    interface PlantButtonItem {
    }
    interface PlantCard {
    }

    interface PlantButtonAttributes {
        "type": "button" | "reset" | "submit";
    }

    interface IntrinsicElements {
        "plant-button": Omit<PlantButton, keyof PlantButtonAttributes> & { [K in keyof PlantButton & keyof PlantButtonAttributes]?: PlantButton[K] } & { [K in keyof PlantButton & keyof PlantButtonAttributes as `attr:${K}`]?: PlantButtonAttributes[K] } & { [K in keyof PlantButton & keyof PlantButtonAttributes as `prop:${K}`]?: PlantButton[K] };
        "plant-button-item": PlantButtonItem;
        "plant-card": PlantCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "plant-button": LocalJSX.IntrinsicElements["plant-button"] & JSXBase.HTMLAttributes<HTMLPlantButtonElement>;
            "plant-button-item": LocalJSX.IntrinsicElements["plant-button-item"] & JSXBase.HTMLAttributes<HTMLPlantButtonItemElement>;
            "plant-card": LocalJSX.IntrinsicElements["plant-card"] & JSXBase.HTMLAttributes<HTMLPlantCardElement>;
        }
    }
}
